name: Lint Shell
on:
  workflow_call:
    inputs:
      ignore:
        default: SENTINEL
        type: string
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt update
          sudo apt install devscripts shellcheck shfmt
      - run: checkbashisms $(shfmt -f . | grep -v ${{ inputs.ignore }})
      - run: shellcheck $(shfmt -f .)
      - run: shfmt -d -i 4 -sr $(shfmt -f .)
